-- Create ref_codes table
CREATE TABLE public.ref_codes (
  code BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('signup_cliente', 'signup_revenda', 'invite_user', 'trial_cliente')),
  owner_tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  payload JSONB DEFAULT '{}'::jsonb,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.ref_codes ENABLE ROW LEVEL SECURITY;

-- RLS: Members of owner_tenant can read their codes
CREATE POLICY "Owner tenant members can view their ref_codes"
ON public.ref_codes
FOR SELECT
USING (owner_tenant_id = current_tenant_id());

-- RLS: Admins of owner tenant can create codes
CREATE POLICY "Owner tenant admins can create ref_codes"
ON public.ref_codes
FOR INSERT
WITH CHECK (
  owner_tenant_id = current_tenant_id() 
  AND is_tenant_admin(auth.uid(), current_tenant_id())
);

-- RLS: Admins can update their tenant's codes
CREATE POLICY "Owner tenant admins can update ref_codes"
ON public.ref_codes
FOR UPDATE
USING (owner_tenant_id = current_tenant_id() AND is_tenant_admin(auth.uid(), current_tenant_id()))
WITH CHECK (owner_tenant_id = current_tenant_id() AND is_tenant_admin(auth.uid(), current_tenant_id()));

-- RLS: Admins can delete their tenant's codes
CREATE POLICY "Owner tenant admins can delete ref_codes"
ON public.ref_codes
FOR DELETE
USING (owner_tenant_id = current_tenant_id() AND is_tenant_admin(auth.uid(), current_tenant_id()));

-- Public function to validate ref_code (no auth required)
CREATE OR REPLACE FUNCTION public.validate_ref_code(_code BIGINT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _ref_code RECORD;
BEGIN
  SELECT code, kind, owner_tenant_id, payload, active
  INTO _ref_code
  FROM public.ref_codes
  WHERE code = _code AND active = true;

  IF NOT FOUND THEN
    RETURN json_build_object('valid', false, 'error', 'Código inválido ou expirado');
  END IF;

  RETURN json_build_object(
    'valid', true,
    'code', _ref_code.code,
    'kind', _ref_code.kind,
    'owner_tenant_id', _ref_code.owner_tenant_id,
    'payload', _ref_code.payload
  );
END;
$$;

-- RPC to process signup with ref_code
CREATE OR REPLACE FUNCTION public.process_ref_code_signup(_code BIGINT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _user_id UUID;
  _ref_code RECORD;
  _new_tenant_id UUID;
  _tenant_type TEXT;
  _parent_tenant_id UUID;
  _owner_tenant_id UUID;
BEGIN
  _user_id := auth.uid();

  IF _user_id IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'User must be authenticated');
  END IF;

  -- Get ref_code
  SELECT code, kind, owner_tenant_id, payload, active
  INTO _ref_code
  FROM public.ref_codes
  WHERE code = _code AND active = true;

  IF NOT FOUND THEN
    RETURN json_build_object('success', false, 'error', 'Código inválido ou expirado');
  END IF;

  -- Determine tenant type and relationships based on kind
  CASE _ref_code.kind
    WHEN 'signup_cliente', 'trial_cliente' THEN
      _tenant_type := 'cliente';
      _parent_tenant_id := _ref_code.owner_tenant_id;
      _owner_tenant_id := _ref_code.owner_tenant_id;
    WHEN 'signup_revenda' THEN
      _tenant_type := 'revenda';
      _parent_tenant_id := _ref_code.owner_tenant_id;
      _owner_tenant_id := NULL;
    WHEN 'invite_user' THEN
      -- For invite_user, just add user to existing tenant
      INSERT INTO public.tenant_members (tenant_id, user_id, role_in_tenant, status)
      VALUES (_ref_code.owner_tenant_id, _user_id, 'user', 'active')
      ON CONFLICT DO NOTHING;
      
      UPDATE public.profiles
      SET current_tenant_id = _ref_code.owner_tenant_id
      WHERE user_id = _user_id;

      RETURN json_build_object(
        'success', true,
        'message', 'User added to tenant',
        'tenant_id', _ref_code.owner_tenant_id
      );
  END CASE;

  -- Create new tenant
  INSERT INTO public.tenants (type, parent_tenant_id, owner_tenant_id, name, status)
  VALUES (
    _tenant_type,
    _parent_tenant_id,
    _owner_tenant_id,
    COALESCE(_ref_code.payload->>'tenant_name', 'Novo ' || _tenant_type),
    'active'
  )
  RETURNING id INTO _new_tenant_id;

  -- Add user as owner of new tenant
  INSERT INTO public.tenant_members (tenant_id, user_id, role_in_tenant, status)
  VALUES (_new_tenant_id, _user_id, 'owner', 'active');

  -- Set current tenant
  UPDATE public.profiles
  SET current_tenant_id = _new_tenant_id
  WHERE user_id = _user_id;

  RETURN json_build_object(
    'success', true,
    'message', 'Tenant created successfully',
    'tenant_id', _new_tenant_id,
    'tenant_type', _tenant_type
  );
END;
$$;